[lib]
name = "human_detector"
crate-type = ["cdylib"]  # For dynamic library

[dependencies]
opencv = { version = "0.86", features = ["opencv-4", "buildtime-bindgen"] }
pyo3 = { version = "0.18", features = ["extension-module"] }
anyhow = "1.0"
